anomaly:
  wrong_way_angle_tolerance: 50
cameras:
  east:
    exclusion_zones: []
    lane_mask:
    - 0.1
    - 0.1
    - 0.85
    - 0.1
    - 0.85
    - 0.7792
    - 0.1
    - 0.7792
    tripwire_a:
    - 0.3312
    - 0.3931
    - 0.6977
    - 0.4083
    tripwire_b:
    - 0.1031
    - 0.3806
    - 0.8211
    - 0.5194
  north:
    exclusion_zones: []
    lane_mask:
    - 0.1
    - 0.1
    - 0.85
    - 0.1
    - 0.85
    - 0.8
    - 0.1
    - 0.8
    tripwire_a:
    - 0.2305
    - 0.4931
    - 0.6687
    - 0.3486
    tripwire_b:
    - 0.0031
    - 0.8333
    - 0.957
    - 0.3319
  south:
    exclusion_zones: []
    lane_mask:
    - 0.15
    - 0.1
    - 0.7
    - 0.1
    - 0.7
    - 0.8
    - 0.15
    - 0.8
    tripwire_a:
    - 0.2305
    - 0.3042
    - 0.2516
    - 0.3458
    - 0.2773
    - 0.3875
    - 0.3273
    - 0.4056
    - 0.3641
    - 0.4056
    - 0.4656
    - 0.3417
    - 0.6484
    - 0.3306
    tripwire_b:
    - 0.2172
    - 0.3056
    - 0.218
    - 0.4514
    - 0.2516
    - 0.6667
    - 0.3297
    - 0.6722
    - 0.9938
    - 0.4806
